language: ruby
cache: bundler
rvm:
  - 2.6.3

env:
  - RAILS_ENV=test REGISTRATION_PASSPHRASE=DasisteinTest

before_install:
  - gem update --system
  - gem install bundler

script:
  - bundle exec rake db:create
  - bundle exec rake db:schema:load
  - bin/rails db:migrate RAILS_ENV=test
  - bundle exec rake test
