language: ruby
cache: bundler
rvm:
  - 2.6.3

env:
  - DB=sqlite REGISTRATION_PASSPHRASE=DasisteinTest

before_install:
  - gem update --system
  - gem install bundler

before_script:
  - cp config/database.travis.yml config/database.yml

script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - xvfb-run bundle exec rake
