version: "3.7"
services:
  db:
    container_name: xronos_postgres_db
    restart: always
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - docker_env_variables.env
  web:
    container_name: xronos_rails_app
    restart: always
    image: xchronosch/xronos.rails
    ports:
      - "4000:3000"
    depends_on:
      - db
    env_file:
      - docker_env_variables.env

