version: "3.7"
services:
  db:
    container_name: xronos_postgres_db
    restart: always
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./db:/var/lib/postgresql/data
    env_file:
      - env_variables.env
    labels:
      - "autoheal=true"
    healthcheck:
      test: curl --fail http://localhost:4001/ || exit 1
        interval: 2m
        timeout: 30s
        retries: 3
        start_period: 5m
  web:
    container_name: xronos_rails_staging_app
    restart: always
    image: xronos/xronos.rails.staging
    ports:
      - "4001:3000"
    depends_on:
      - db
    env_file:
      - env_variables.env
  autoheal:
    image: willfarrell/autoheal:latest
    tty: true
    restart: always
    environment:
      - AUTOHEAL_INTERVAL=60
      - AUTOHEAL_START_PERIOD=300
      - AUTOHEAL_DEFAULT_STOP_TIMEOUT=10
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
