 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/dendros", type: :request do
  # Dendro. As you add validations to Dendro, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Dendro.create! valid_attributes
      get dendros_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      dendro = Dendro.create! valid_attributes
      get dendro_url(dendro)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_dendro_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      dendro = Dendro.create! valid_attributes
      get edit_dendro_url(dendro)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Dendro" do
        expect {
          post dendros_url, params: { dendro: valid_attributes }
        }.to change(Dendro, :count).by(1)
      end

      it "redirects to the created dendro" do
        post dendros_url, params: { dendro: valid_attributes }
        expect(response).to redirect_to(dendro_url(Dendro.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Dendro" do
        expect {
          post dendros_url, params: { dendro: invalid_attributes }
        }.to change(Dendro, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post dendros_url, params: { dendro: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested dendro" do
        dendro = Dendro.create! valid_attributes
        patch dendro_url(dendro), params: { dendro: new_attributes }
        dendro.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the dendro" do
        dendro = Dendro.create! valid_attributes
        patch dendro_url(dendro), params: { dendro: new_attributes }
        dendro.reload
        expect(response).to redirect_to(dendro_url(dendro))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        dendro = Dendro.create! valid_attributes
        patch dendro_url(dendro), params: { dendro: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested dendro" do
      dendro = Dendro.create! valid_attributes
      expect {
        delete dendro_url(dendro)
      }.to change(Dendro, :count).by(-1)
    end

    it "redirects to the dendros list" do
      dendro = Dendro.create! valid_attributes
      delete dendro_url(dendro)
      expect(response).to redirect_to(dendros_url)
    end
  end
end
