# config/static/xronos.yml
title: "Acknowledgements"
splash: 'acknowledgement_hero.jpg'
sections:
  - heading: "Current XRONOS"
    content: |
      XRONOS is currently maintained by Martin Hinz and Joe Roe at the Institute of Archaeological Sciences, University of Bern, supported by the [Swiss National Science Foundation](https://www.snf.ch/en) ([SNSF Project #198152](https://data.snf.ch/grants/grant/198153)).

  - heading: "Former Project Team Members"
    items:
      - "Caroline Heitz (2019)"
      - "Clemens Schmid (2019)"
      - "Setareh Ebrahimiabareghi (2022)"

  - heading: "Collaborators"
    items:
      - name: "Beat Eberschweiler"
        link: "https://www.stadt-zuerich.ch/hbd/de/index/ueber_das_departement/organisation/gremium/denkmalpflegekommission/beat_eberschweiler.html"
        description: "cantonal archaeologist (director), Baudirektion, Amt für Raumentwicklung, Kanton Zürich"
      - name: "Sönke Szidat"
        link: "https://www.14c.unibe.ch/about_us/team/lara_team/prof_dr_szidat_soenke/index_eng.html"
        description: "Head of research group, LARA, Department of Chemistry and Biochemistry, University of Bern"
      - name: "Tomasz J. Chmielewski"
        description: "independent scholar, Wrocław, Poland (Poland, Hungary, Slovakia and the Czech Republic)"

  - heading: "Contributing Datasets"
    content: "XRONOS is continuously updated with data from a number of existing databases, including:"
    items:
      - name: "14SEA"
        link: "http://www.14sea.org/"
        description: "maintained by Agathe Reingruber and Laurens Thissen"
      - name: "ADRAC"
        link: "https://github.com/dirkseidensticker/aDRAC"
        description: "maintained by Dirk Seidensticker, Wannes Hubau and Katharina V. M. Jungnickel"
      - name: "AIDA"
        link: "https://github.com/apalmisano82/AIDA"
        description: "maintained by Alessio Palmisano, Andrew Bevan, Alex Kabelindde, Neil Roberts & Stephen Shennan"
      - name: "BDA"
        link: "https://bda.huma-num.fr"
        description: "maintained by Thomas Perrin"
      - name: "CalPal"
        link: "https://doi.org/10.5281/zenodo.7215741"
        description: "maintained by Bernhard Weninger"
      - name: "caribbean-14C"
        link: "https://github.com/philriris/caribbean-14C"
        description: "maintained by Phil Riris"
      - name: "CONTEXT"
        link: "http://context-database.uni-koeln.de/"
        description: "maintained by U. Böhner & D. Schyle"
      - name: "EUBAR"
        link: "https://telearchaeology.org/eubar-c14-database/"
        description: "maintained by Gacomo Capuzzo"
      - name: "IRDD"
        link: "https://sites.google.com/site/chapplearchaeology/irish-radiocarbon-dendrochronological-dates/download"
        description: "maintained by Robert M. Chapple"
      - name: "MedAfriCarbon"
        link: "https://theia.arch.cam.ac.uk/MedAfriCarbon/"
        description: "maintained by Giulio Lucarini"
      - name: "MesoRAD"
        link: "https://www.mesorad.com/"
        description: "maintained by Julie Hoggarth and Claire Ebert"
      - name: "NERD"
        link: "https://github.com/apalmisano82/NERD"
        description: "maintained by Alessio Palmisano, Andrew Bevan, Dan Lawrence and Stephen Shennan"
      - name: "p3k14c"
        link: "https://www.p3k14c.org/"
        description: "maintained by the PEOPLE3000 Working Group"
      - name: "RADON"
        link: "https://radon.ufg.uni-kiel.de/"
        description: "maintained by Martin Hinz & Christoph Rinne"
      - name: "rxpand"
        link: "https://github.com/jgregoriods/rxpand"
        description: "maintained by Jonas Gregorio de Souza"
      - name: "Southern African Radiocarbon Database"
        link: "https://github.com/emmaloftus/Southern-African-Radiocarbon-Database"
        description: "maintained by Emma Loftus"

  - heading: "Published Compilations"
    items:
      - name: "Böhner, U. and Schyle, D., 2004."
        link: "https://web.archive.org/web/20161224034255/http://context-database.uni-koeln.de/"
        description: "Radiocarbon CONTEXT database."
      - name: "Capuzzo, G., Boaretto, E., and Barceló, J. A., 2014."
        link: "https://doi.org/10.2458/56.17453"
        description: "EUBAR: A database of 14C measurements for the European Bronze Age. A Bayesian analysis of 14C-dated archaeological contexts from Northern Italy and Southern France. *Radiocarbon* 56(2): 851-69."
      - name: "Courtney Mustaphi, Colin, 2016."
        link: "https://doi.org/10.7910/DVN/NJLNRJ"
        description: "Radiocarbon dates from eastern Africa in the CARD2.0 format. *Harvard Dataverse*."
      - name: "Crema, E.R., Kobayashi, K., 2020."
        link: "https://doi.org/10.1016/j.jas.2020.105136"
        description: "A multi-proxy inference of Jōmon population dynamics using bayesian phase models, residential data, and summed probability distribution of 14C dates. *Journal of Archaeological Science* 117: 105136."
      - name: "D'Errico, F., Banks, W. E., Vanharen, M., Laroulandie, V., and Langlais, M., 2011."
        link: "https://doi.org/10.4207/PA.2011.ART40"
        description: "PACEA Geo-Referenced Radiocarbon Database. *PaleoAnthropology* 2011: 1–12."
      - name: "Katsianis, M., Bevan, A., Styliaras, G., and Maniatis, Y., 2020."
        link: "https://doi.org/10.5334/joad.65"
        description: "An Aegean history and archaeology written through radiocarbon dates. *Journal of Open Archaeology Data* 8: 5."
      - name: "Manning, K., Colledge, S., Crema, E., Shennan, S. and Timpson, A., 2016."
        link: "https://doi.org/10.5334/joad.40"
        description: "The Cultural Evolution of Neolithic Europe. EUROEVOL Dataset 1: Sites, Phases and Radiocarbon Data. *Journal of Open Archaeology Data* 5: 2."
      - name: "Martínez-Grau, H., Morell-Rovira, B., and Antolín, F., 2021."
        link: "https://doi.org/10.5334/joad.72"
        description: "Radiocarbon Dates Associated to Neolithic Contexts (Ca. 5900 – 2000 Cal BC) from the Northwestern Mediterranean Arch to the High Rhine Area. *Journal of Open Archaeology Data* 9: 1."
      - name: "Palmisano, A., Bevan, A., and Shennan, S., 2018."
        link: "https://doi.org/10.5334/joad.43"
        description: "Regional Demographic Trends and Settlement Patterns in Central Italy: Archaeological Sites and Radiocarbon Dates. *Journal of Open Archaeology Data* 6: 2."
      - name: "Williams, A. and Ulm, S., 2014."
        link: "https://doi.org/10.5284/1027216"
        description: "AustArch: A Database of 14C and Luminescence Ages from Archaeological Sites in Australia. *Archaeology Data Service*."

  - heading: "Graphics and Photos"
    items:
      - name: "Book"
        link: "https://thenounproject.com/icon/book-5433144/"
        description: "by HDM"
      - name: "006 Carbon C"
        link: "https://thenounproject.com/icon/006-carbon-c-1022338/"
        description: "by Joel Wisneski"
      - name: "Pottery"
        link: "https://thenounproject.com/icon/pottery-3969143/"
        description: "by Adrien Coquet"
      - name: "Ruin"
        link: "https://thenounproject.com/icon/ruin-568421/"
        description: "by João Archer"
      - name: "Wood Texture"
        link: "https://thenounproject.com/icon/wood-texture-3674579/"
        description: "by Laura"

  - heading: "Additional Data and Services"
    content: "Geocoding via [Nominatim](https://nominatim.org/). Data ⓒ [OpenStreetMap contributors](https://www.openstreetmap.org/copyright)."