name: CI

on:
  [push, workflow_dispatch]
    

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:11
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports: ['5432:5432']
        options:
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install boost
        run: sudo apt-get install -y --no-install-recommends build-essential libboost-all-dev firefox
      - uses: actions/checkout@v2
      - name: Make Calibrator
        run: |
          cd vendor/calibrator
          make clean
          make
          mv bin/calibrator bin/calibrator_linux
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
      - name: Ruby gem cache
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-
      - name: Install gems
        run: |
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.19.0
      - name: Find yarn cache location
        id: yarn-cache
        run: echo "::set-output name=dir::$(yarn cache dir)"
      - name: JS package cache
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install packages
        run: |
          yarn install --pure-lockfile
      - name: precompile asstes
        run: bundle exec rake assets:precompile
      - name: Setup test database
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: "postgres"
          REGISTRATION_PASSPHRASE: ""
        run: |
          bin/rails db:setup
      - name: Run tests
        run: COVERAGE=true bundle exec rspec
        env:
          RAILS_ENV: test
          PGHOST: localhost
          PGUSER: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: myapp_test
          POSTGRES_PASSWORD: "postgres"
          REGISTRATION_PASSPHRASE: ""
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
